export const layoutInteractionType = {

    CHANGE_COLLAPSED_SIDER: "CHANGE_COLLAPSED_SIDER",

    CHANGE_SEARCH: "CHANGE_SEARCH",

    SET_HEADER: "SET_HEADER",

    ON_CHANGE_VISIBLE_DRAWER: "ON_CHANGE_VISIBLE_DRAWER",

    ON_RELOAD_DATA: "ON_RELOAD_DATA",

    ON_CHANGE_SCREEN_WIDTH: "ON_CHANGE_SCREEN_WIDTH",

    CHANGE_SETTING_SIDER: "CHANGE_SETTING_SIDER",

    ON_CHANGE_VISIBLE_DRAWER_ADMIN: "ON_CHANGE_VISIBLE_DRAWER_ADMIN",

}
